name: simple_note_app

description: A simple note application using Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.0

  # Local Database
  sqflite: ^2.3.0
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.9.0
  path_provider: ^2.1.0

  # Date Format
  intl: ^0.18.0

  # Toast Message
  fluttertoast: ^8.2.2

  # Save Theme
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true